name: Deploy Laravel to EC2 with rsync

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_ci
          chmod 600 ~/.ssh/github_ci
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            --exclude "node_modules" \
            --exclude "storage/logs" \
            --exclude "storage/app/public" \
            --exclude ".env" \
            --exclude "tests" \
            --exclude "vendor" \
            --exclude "public/storage" \
            -e "ssh -i ~/.ssh/github_ci" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/api

      - name: Run Laravel commands on EC2
        run: |
          ssh -i ~/.ssh/github_ci ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/api
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart php8.2-fpm # adjust if you're using nginx/apache
          EOF
